### PR TITLE
fix: quoted properties of `ObjectExpression` not in exports proxy

### LINKED ISSUE #93: `parseModule` does not include object properties with quotes in their names
### Environment

```
$ node -v
v18.17.1

$ pnpm -v
8.7.5

$ cat package.json | grep magicast
    "magicast": "^0.3.1",
```

### Reproduction

```js
import { parseModule } from "magicast";

const mod = parseModule(`
export default defineConfig({
  test: {
    thisIsOk: {
      key: 111,
    },

    "thisIsBroken": {
      key: 222,
    },

    'thisIsAlsoBroken': {
      key: 333,
    },
  },
});
`);

const options =
  mod.exports.default.$type === "function-call"
    ? mod.exports.default.$args[0]
    : mod.exports.default;

console.log("test.thisIsOk", options.test.thisIsOk?.key); // ✅
console.log("test.thisIsBroken", options.test.thisIsBroken?.key); // ❌
console.log("test.thisIsAlsoBroken", options.test.thisIsAlsoBroken?.key); // ❌

// Let's see if quotes are included in key names...
console.log("test.thisIsBroken#2", options.test['"thisIsBroken"']?.key); // ❌
console.log("test.thisIsAlsoBroken#2", options.test["'thisIsAlsoBroken'"]?.key); // ❌
```

```
test.thisIsOk 111
test.thisIsBroken undefined
test.thisIsAlsoBroken undefined
test.thisIsBroken#2 undefined
test.thisIsAlsoBroken#2 undefined
```

### Describe the bug

It's not possible to access object properties that have quotes in their property names. Properties without quotes work fine.

In my use-case object properties can be glob-patterns so they need to be wrapped. Object keys like `"**/utils/**"` must be wrapped:

```ts
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    coverage: {
      thresholds: {
        // Thresholds for all files
        lines: 100,
        functions: 100,
        branches: 80,
        statements: 90,

        // Thresholds for utilities
        "**/utils/**": {
          lines: 80,
          statements: 50,
        },
      },
    },
  },
});
```

### Additional context

https://github.com/vitest-dev/vitest/pull/4442

### Logs

_No response_

### PR DESCRIPTION
**Pull request by AriPerkkio**
### 🔗 Linked issue

- Fixes #93

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

When traversing the `c` of following:

```js
export default {
  foo: {
    "c": { key: 5 },
    'd': { key: 6 },
  }
}
```

https://github.com/unjs/magicast/blob/32be90efe6be8036088c0a6c39c740f3f0efb13a/src/proxy/object.ts#L31

```js
> prop.value.value
undefined

> prop.value
Node {
  type: 'ObjectExpression',
  start: 35,
  end: 45,
  loc: SourceLocation { ... },
  properties: [
    Node {
      type: 'ObjectProperty',
      start: 37,
      end: 43,
      loc: [SourceLocation],
      method: false,
      key: [Node],
      computed: false,
      shorthand: false,
      value: [Node]
    }
  ]
}
```

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/proxy/object.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ export function proxifyObject<T extends object>(
           prop.key.type === "BooleanLiteral") &&
         prop.key.value.toString() === key
       ) {
-        return (prop.value as any).value;
+        return (prop.value as any).value || prop.value;
```
Comment (manniL) [inline src/proxy/object.ts:31]: I'd suggest using the nullish coalescing operator here so we make sure we don't accidentally skip `0` or `''`

```suggestion
        return (prop.value as any).value ?? prop.value;
```
