### PR TITLE
fix!: `writeFile` now requires filename 

### LINKED ISSUE #66: ProxifiedModule<Exports> is not compatible with writeFile().
### Environment

magicast@0.2.9
typescript@5.1.6

### Reproduction

https://stackblitz.com/edit/typescript-hjtg2e?file=index.ts,node_modules%2Fmagicast%2Fdist%2Findex.d.ts

## stackblitz 
image

## stackblitz - Definition
image

## my-vscode

So, I must `const ast = mod.$ast;`

image

### Additional context

This is a  feature or bug?

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Barbapapazes**
### 🔗 Linked issue

fix #66
close #76

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR solve a type issue and add some tests.

And because `recast`, https://github.com/benjamn/recast/blob/master/lib/parser.ts#L24, does not pass the filename to the parser option, we can't use it as the output filename.

_I'm not sure if how tests are written is the best way to do it, so feel free to change it if you have a better idea._

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

File: src/code.ts [hunk 1]
```diff
@@ -77,13 +77,13 @@ export async function loadFile<Exports extends object = any>(
...
-  node: { ast: ASTNode } | ASTNode,
+  node: { $ast: ASTNode } | ASTNode,
   filename?: string,
   options?: ParseOptions
 ): Promise<void> {
-  const ast = "ast" in node ? node.ast : node;
+  const ast = "$ast" in node ? node.$ast : node;
   const { code, map } = generateCode(ast, options);
-  filename = filename || (ast as any).name || "output.js";
+  filename = filename || "output.js";
```
Comment (antfu) [inline src/code.ts:86]: I kinda forgot why we have this optional. Maybe instead we could just make it mandatory.  A implicit file name feels weird.

Comment (Barbapapazes) [reply src/code.ts]: Updated!

**Review by antfu — APPROVED** [review]
